# Options for analysis running.
run:
  go: '1.23'

linters:
  fast: true
  disable-all: true
  enable:
    # Defaults
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Extras
    - asciicheck
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - forbidigo
    - forcetypeassert
    # - gochecknoglobals
    - gochecknoinits
    - gocritic
    - gofumpt
    - goimports
    - goprintffuncname
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

issues:
  exclude-rules:
    - linters:
        - forbidigo
      text: "Print(|f|ln)|print|println"

    - path: '(.+)_test\.go'
      linters:
        - unused

severity:
  default-severity: error

linters-settings:
  gofumpt:
    # Module path which contains the source code being formatted.
    # Default: ""
    # Choose whether or not to use the extra rules that are disabled
    # by default
    extra-rules: true
